### PR TITLE
Add support for a classic UNION within CTEs

### PR DESCRIPTION
**Pull request by Nemrtvej**
Hello, 
first of all, I'd like to thank you for your package as it helped me recently with a dynamic DBAL Query utilizing common table expressions.

However I also needed a way to insert UNION into those subqueries. I come up with a really crude but working solution. 

In this MR, I'd like to ask you if you could add official support of this feature and if you would consider and perhaps improve this implementation. 

If you would like to tinker of the result of this query, I set up a db-fiddle for it  - https://www.db-fiddle.com/f/v9CixkP6nrNaJgxRRHwNf4/0

If the fiddle gets deleted in the future, the schema is 

```sql

CREATE TABLE people (id uuid, full_name text);
CREATE TABLE companies (id uuid, company_name text);
CREATE TABLE planets (id uuid, planet_name text);


INSERT INTO people (id, full_name) VALUES 

('2ceb85e2-4468-480b-9042-ea62b23dc680', 'John Doe'),
('cd106020-2895-484c-b24f-6b772c77e53e', 'Jane Doe'),
('aed39e39-d4a7-4972-bb81-97d9d83458c4', 'Robin Hood');


INSERT INTO companies (id, company_name) VALUES 

('f3581f07-71bc-4d0e-97ff-bacbbd87e6c8', 'ACME inc.'),
('3146a69e-79bb-4f62-9877-13253a904b44', 'EVIL inc.'),
('3dd72c66-a8e4-4b8d-85f8-87dfa3a2989a', 'GOOD inc.');


INSERT INTO planets (id, planet_name) VALUES 

('41e112a4-ee09-45e3-aeae-2df07d8d029e', 'Mercury'),
('8f8fcef2-43d5-4532-96e7-53dd73c7d577', 'Venus'),
('ffa30d4d-a465-4983-868b-d5cc0c612182', 'Pluto');

```

and the Query is 

```sql 



WITH reported_objects as (

  SELECT 
      p.id,
      p.full_name as object_name,
      'person' as type
  FROM people p
  WHERE p.id = '2ceb85e2-4468-480b-9042-ea62b23dc680'

  
  UNION 
  
  SELECT 
      c.id,
      c.company_name as object_name,
      'company' as type
  FROM companies c 
  WHERE c.id = '2ceb85e2-4468-480b-9042-ea62b23dc680'
  
  UNION 
  
  SELECT 
      p.id,
      p.planet_name as object_name,
      'planet' as type
  FROM planets p
  WHERE p.id = '2ceb85e2-4468-480b-9042-ea62b23dc680'
)

SELECT
  ro.id,
  ro.object_name,
  ro.type
FROM reported_objects ro 
ORDER BY object_name ASC
```

Thank you for your project and time and have a nice day!

### CODE REVIEW

**Comment by dave-redfern** [comment]
@Nemrtvej Thanks for your PR! I think I may have a better idea on how to handle this by adding UNION support directly to the `Expression` object instead. I am currently experimenting with it and will let you know on progress.

With that said: I am almost ready to publish a query builder library that can better handle all of these things with a better API, though it will be experimental for a while.

**Comment by dave-redfern** [comment]
@Nemrtvej I've added a PR that adds UNION to the expression object itself as well as porting over your original test for the building. Please take a look and let me know your thoughts.

**Comment by Nemrtvej** [comment]
Hello @dave-redfern, 
thank you for looking at my issue! 
I've tried your new approach and it works correctly in my case. 

I think your version is way better than mine and I would be more than happy if you closed my pull request and released a new version with your approach :-). 

Thank you very much and have a nice day.

**Comment by dave-redfern** [comment]
Closing in favour of PR #5

**Pull request closed without merging**
